//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChampionshipWorldSkills.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("237, 28, 41")]
        public global::System.Drawing.Color Red {
            get {
                return ((global::System.Drawing.Color)(this["Red"]));
            }
            set {
                this["Red"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("23, 71, 158")]
        public global::System.Drawing.Color Blue {
            get {
                return ((global::System.Drawing.Color)(this["Blue"]));
            }
            set {
                this["Blue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("249, 157, 28")]
        public global::System.Drawing.Color Yellow {
            get {
                return ((global::System.Drawing.Color)(this["Yellow"]));
            }
            set {
                this["Yellow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("36, 159, 69")]
        public global::System.Drawing.Color Green {
            get {
                return ((global::System.Drawing.Color)(this["Green"]));
            }
            set {
                this["Green"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("35, 31, 32")]
        public global::System.Drawing.Color Black {
            get {
                return ((global::System.Drawing.Color)(this["Black"]));
            }
            set {
                this["Black"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color White {
            get {
                return ((global::System.Drawing.Color)(this["White"]));
            }
            set {
                this["White"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("167, 169, 172")]
        public global::System.Drawing.Color Gray {
            get {
                return ((global::System.Drawing.Color)(this["Gray"]));
            }
            set {
                this["Gray"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tahoma, 12pt")]
        public global::System.Drawing.Font FontMain {
            get {
                return ((global::System.Drawing.Font)(this["FontMain"]));
            }
            set {
                this["FontMain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tahoma, 15.75pt, style=Bold")]
        public global::System.Drawing.Font FontCaption {
            get {
                return ((global::System.Drawing.Font)(this["FontCaption"]));
            }
            set {
                this["FontCaption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tahoma, 12pt, style=Bold")]
        public global::System.Drawing.Font FontSubcaption {
            get {
                return ((global::System.Drawing.Font)(this["FontSubcaption"]));
            }
            set {
                this["FontSubcaption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("209, 211, 212")]
        public global::System.Drawing.Color LightGray {
            get {
                return ((global::System.Drawing.Color)(this["LightGray"]));
            }
            set {
                this["LightGray"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ПК-2-ПК\\KELITESQL;Initial Catalog=ChampionshipWorldSkills;Integrated " +
            "Security=True")]
        public string ConnectionString {
            get {
                return ((string)(this["ConnectionString"]));
            }
            set {
                this["ConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RememberedUserLogin {
            get {
                return ((string)(this["RememberedUserLogin"]));
            }
            set {
                this["RememberedUserLogin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RememberedUserPassword {
            get {
                return ((string)(this["RememberedUserPassword"]));
            }
            set {
                this["RememberedUserPassword"] = value;
            }
        }
    }
}
